name: tests

on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * *'

jobs:
  tests:
    name: PHP ${{ matrix.php }} on ${{ matrix.os }}

    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false

      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        php: ['7.3', '7.4', '8.0']

    steps:
      - uses: actions/checkout@v2

      - name: Setup PHP, Tools and Extensions
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          tools: composer:v2, phpunit:9.4.4, php-cs-fixer
          extensions: dom, fileinfo, mbstring, pdo_mysql, pdo_sqlite, sqlite3, xdebug

      - name: Add nunomaduro/larastan to dev dependencies
        run: composer require nunomaduro/larastan --dev --no-progress --no-interaction

      - name: Run PHPStan
        run: vendor/bin/phpstan analyse --memory-limit=-1 -vvv

      - name: Run PHP-CS-Fixer
        run: php-cs-fixer fix --dry-run -vvv

      - name: Run PHPUnit
        run: phpunit -d memory_limit=-1 -vvv
